services:
  postgres:
    image: postgres:15
    container_name: bodegaSena-php
    environment:
      POSTGRES_DB: ${DB_DATABASE}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - postgres_php:/var/lib/postgresql/data
volumes:
  postgres_php:

